spring.application.name=aeropuerto-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/aeropuertolosprimos
spring.datasource.username=usuario_bd
spring.datasource.password=contrasena_bd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

app.jwt.secret=colocar_clave_segura_minimo_32_caracteres